### ISSUE TITLE
Unable to import component: No module named 'bs4'

### ISSUE THREAD

**Issue by viroge** [ZsBT/hass-w1000-portal#11]
Hello, 

I've just installed this integration in my homeassistant and after restart I got this error:

Logger: homeassistant.setup
Source: setup.py:210
First occurred: 17:54:32 (1 occurrences)
Last logged: 17:54:32

Setup failed for custom integration w1000-energy-monitor: Unable to import component: No module named 'bs4'

After installing bs4 manually it works:

source /srv/homeassistant/bin/activate
pip install beautifulsoup4

I don't speak python a'la homeassistant, but I assume this should be added as a dependency. 

Thanks for this btw! :)

Regards,
Gabor

**Comment by ZsBT** [comment]
Thanks Gábor, you're right: this should be a dependency.
