### ISSUE TITLE
Unsupported state class

### ISSUE THREAD

**Issue by buczekpaya** [ZsBT/hass-w1000-portal#22]
After upgrade HomeAssistant to version 2023.8.2 it shows 2 errors (for sensor.w1000_import and sensor.w1000_export):

>Unsupported state class
The state class of this entity, is not supported.
Statistics cannot be generated until this entity has a supported state class.
If this state class was provided by an integration, this is a bug. Please report an issue.
If you have set this state class yourself, please correct it. The different state classes and when to use which can be found in the developer documentation. If the state class has permanently changed, you may want to remove the long term statistics of it from your database.
Do you want to permanently remove the long term statistics of sensor.w1000_import from your database?

Is this really a bug? What could I do to fix this issue?

By,

paya

**Comment by ZsBT** [comment]
I'm afraid it is indeed the fault of the integration. I'll check it out with this version soon.

**Comment by buczekpaya** [comment]
I've opened HomeAssistant to check any change of issue, and the errors are disappeared... I don't know how...

**Comment by ZsBT** [comment]
Closing this as not reproducible.
