### ISSUE TITLE
1.8.0 curve is missing

### ISSUE THREAD

**Issue by hunhejj** [ZsBT/hass-w1000-portal#30]
Hozzáadtam az `A+`-t, viszont olyan görbét nem találok, hogy `1.8.0`. Ez mit takar? Csak A+,A-,R+,R- közül lehet az EON-nál választani.

**Comment by zee36** [comment]
![Screenshot 2024-04-05 210653](https://github.com/ZsBT/hass-w1000-portal/assets/130402676/20f65b01-55a6-4820-844a-63c1231c3581)

Szia, ezek azok. Ha bevalogotod a riportba EON tavportalon, latni fogod, hogy melyik hoz ertelmes adatot.

**Comment by hunhejj** [comment]
Szia, nekem csak ezek vannak:
<img width="283" alt="kép" src="https://github.com/ZsBT/hass-w1000-portal/assets/15079374/5aa0be67-a254-4549-a9ad-96e1e9ad181b">

**Comment by zee36** [comment]
Hmm, nekem sajnos nem igy nez ki. Korabban azonban mukodott siman a +/- A gorbekkel is (most azzal nem hoz semmit). 
Elvileg a +/- A gorbek a napi fogyasztas / betaplalast fogjak hozni, az 1.8.0 / 2.8.0 pedig a kumulalt fogyasztast / betaplalast.
Esetleg probald meg , hogy mit hoz a +/- R (nekem olyan opcio nincs), hatha az lesz a Year To Date info.

Meg arra tudok gondolni, hogy ha esetleg uj a rendszered/most regisztraltal akkor meg gyujti az adatot, vagy idobe telik amig atmennek az adatok.

**Comment by hunhejj** [comment]
Sajnos már régóta van fiókom.

Ahogy a kódot elnézem, az `R` nem fog menni, mert fixen `1.8.0`-at vár.

**Comment by ZsBT** [comment]
Szia!
Lehet, hogy a "`HUN`"-izés azonosítód nem lett jól felvéve a portálhoz a regisztráció alkalmával. Az `R` biztosan nem lesz jó, az mást hoz. Szerintem a szolgáltatónak kéne kiegyenesíteni hogy minden görbe elérhető legyen a fiókban.
Zsombor

**Comment by hunhejj** [comment]
Irtam az EON-nak es elerhetove tettek a hianyzo gorbeket. Koszi mindenkinek a segitseget!
