### ISSUE TITLE
Am I doing something wrong...

### ISSUE THREAD

**Issue by orsib78** [ZsBT/hass-w1000-portal#31]
Hello.

I just setup w1000 as per your instructions and I am not sure it's working correctly.
For the import sensor it returns all the energy ever imported to my house, which is good. But for the export it is not showing the number of energy ever exported to the grid, just the actual daily number (which is quite off to what reported by my SolarEdge inverter). Am I doing something wrong or is it an issue with the integration?
It also not clear for me based on your description that how often the integration is polling the data from EON? Can I change it to hourly somehow? (However it doesn't seem the integration refreshing/polling the sensors at all, except when I restarted HA).

![w1000](https://github.com/user-attachments/assets/1bea3889-1a14-4661-8831-81a93dcdca43)

Thanks,
Balazs

**Comment by ZsBT** [comment]
Szia! Az import/export adatok nem tudják a visszamenőleges adatokat produkálni, hanem a napi értéket rögzíti. Amit látsz 9281 az sajnos bug, az utolsó naphoz mindig az aktuális óraállást írja, de másnapra ez javul (azaz mindig az aktuális "tegnap" a napi fogyasztást mutatja, az aktuális "ma" pedig az óraállást). Magyarul, az Energy dashboard a tegnap-tegnapelőtt és visszafele szép, az aktuális mai nap mindig össze van gányolva.
Frissítés naponta történik. Az első időkben negyed óránként volt letöltés, de az EON letiltotta az integráció felhasználóit, mert "leterhelték" a w1000 portált. 
Ez van sajnos.
Mondjuk ahogy olvasom a híreket, a Lölő Országüzemeltető Zrt. az EONt is beszántotta, szóval lehet nem sokáig él ez a projekt...
Zsombor

**Comment by orsib78** [comment]
Hello. Köszi az infókat. Létezik arra valami kulcsrakész megoldás, hogy az okosmérőmön a P1-es portot megtámadva be lehessen huzalozni a szükséges adatokat Home Assistant-ba? Nem riadok vissza egy kis forrasztástól, meg egyéb dologtól, de ha nem kokain árban van, akkor hajlandó lennék egy kulcsra kész megoldást választani, ha létezik ilyen...

**Comment by ZsBT** [comment]
Van bizony, nekem is azt kellett volna, amíg be nem dobozolták atombiztosra a mérőórám.  ESP8266 (Mini D1) alapú cucc, a tápot is a P1-ről kapja és WiFin tolja be HA-ba az adatokat. Ráadásul ott fázisonként is megvannak az adatok, ami a W1000-ben nincs. Nincs már meg fejből a projekt (talán holland), de már rengetegen használják, bevált technika.

**Comment by Stufi007** [comment]
> Hello. Köszi az infókat. Létezik arra valami kulcsrakész megoldás, hogy az okosmérőmön a P1-es portot megtámadva be lehessen huzalozni a szükséges adatokat Home Assistant-ba? Nem riadok vissza egy kis forrasztástól, meg egyéb dologtól, de ha nem kokain árban van, akkor hajlandó lennék egy kulcsra kész megoldást választani, ha létezik ilyen...

Igen, úgy hívják, Homewizard P1. Nem olyan vészes az ára.

**Comment by orsib78** [comment]
Közben beszereztem egy Slimmelezer dobozt és bár nem működik out of the box (mert ugye miért is használnánk úgy a DSMR rendszert, ahogy egész Európában használják), de egy kis hekálás után szépen megy.

**Comment by ZsBT** [comment]
Elvileg infra porton is le lehet kérdezni, szemezgetek a "IEC1107 protocol smart electricity meter infrared" guglis találatokkal.
