### ISSUE TITLE
decrease poll frequency

### ISSUE THREAD

**Issue by ZsBT** [ZsBT/hass-w1000-portal#9]
EON warned some of the users about too frequent data polls.

**Comment by ZsBT** [comment]
fixed by commit, waiting for feedback

**Comment by ZsBT** [comment]
closing as fixed

**Comment by Deadfox531** [comment]
Hello, 
I have the latest version installed and it works very well.  
But eon has just sent an email saying that I am still asking too many questions about the interface.

Could you help with this?

Thanks,
Zsákai Péter

**Comment by ZsBT** [comment]
Hi Péter,

I've just received this EON warning email, too. I asked them to provide
logs as the lastest version is restrictid to 4 logins per day in the early
hours.

Zsombor

**Comment by ZsBT** [comment]
They wrote me I was addressed by a technical accident :)

**Comment by Deadfox531** [comment]
This sounds good😅
